### ISSUE TITLE
Project save fails when starting from scratch

### ISSUE THREAD

**Issue by hsorby** [MusculoskeletalAtlasProject/mapclient#4]
When you use the menu actions to create a new project the project file is valid, but when you start  by creating your workflow immediately the version status is not save to the .workflow.conf file resulting in an invalid workflow configuration.

**Comment by jonathanritchie** [comment]
MusculoskeletalAtlasProject/mapclient-src/pull/2

**Comment by hsorby** [comment]
Fixed
