### ISSUE TITLE
Undo/redo actions do not work for step connections

### ISSUE THREAD

**Issue by tsalemink** [MusculoskeletalAtlasProject/mapclient#82]
### Issue:

The undo and redo actions do not work correctly with the creation and deletion of workflow step connections.

### Steps To Reproduce:

1. Connect two compatible ports with a connection.
2. Delete the connection.
3. Undo the deletion.

The connection will reappear but it is no longer connected to either of the ports. You can test this by moving either of the steps. There is a similar issue happening with the redo action.

**Comment by hsorby** [comment]
Fixed with #92.
